### ISSUE TITLE
Conferences

### ISSUE THREAD

**Issue by aviskase** [postman-toolboxes/api-knowledge#1]
Hi, I was thinking about creating a directory of API-related conferences; similar to https://testingconferences.org/ .

But since you already started gathering API knowledge in one place, maybe it can be done here?

**Comment by kinlane** [comment]
I know of one in the space - https://webapi.events/

I may ask him for a feed.

**Comment by aviskase** [comment]
Doh! How did I forget about it?

Anyway, would be nice to have a link to it on this site.

**Comment by kinlane** [comment]
That is why I create sites like this -- they act as my memory. 

I can't keep up with all the changes anymore. ;-)
